# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Prod stage

FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --pnly=production && npm cache clean --force

COPY --from=builder --chown=nestjs:nodejs /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main"]

