services:
  kanban-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kanban-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    # environment:
    #   - NODE_ENV=${NODE_ENV}
    #   - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-dev
    networks:
      - kanban-dev-network
    restart: unless-stopped

  postgres-dev:
    image: postgres:15-alpine
    container_name: postgres-dev
    env_file:
      - .env.development
    # environment:
    #   - POSTGRES_DB=${DB_NAME}
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - kanban-dev-network
    restart: unless-stopped

volumes:
  postgres-data-dev:

networks:
  kanban-dev-network:
    driver: bridge
